language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: kWxJTM+Y0LyFqYq5FOHGG7dBcsyXUY2xQYLhlAWCUd7jafuiVu750JQmhOcaQL21QLRq3qmGG5yYqrQ9skML6Yv9fcXHZgjazMUEmbv1vjWXjOTIr0G2SstpX/Q1WmxDF2OCzWqdPlQ0q/XUJMNBI0XuojJR20ZHD6c4jSJ5ysAodJObRmxdWpGWYmhox3XOm6WyuZyZ3jPsUG4XIipPigFUHmap4WZ6qi8t/Tz8eW75EueABDzt4lW+a5kAZUkJkp8kn0+3E1+io6WJliOL/ydU24lmS5znVDN6WzZsYo8QnXJMTAniH1+x99iMtAfiUMKDsBB7NYrnyNQMsxGtPeonSMjvZjl5WnveGUoLmm61pBez/yVw4T46eY6rJRyTIDoLse7xWlqMb77KgQIvdOtDNTsyEB607npyrhUYh6hfi6b6IDnNcRjbiDBAmk//A1mZIkE0t0A7iAMkaGYjTfsrSsmyZNiJlmXthUJ72MxIC8xk8OBxxK/UDwUJYXQVHhSwPhnWaJ/mrpch6+bC2x2elsLgxU2/8m9IS2tRwh/3teNdJRsf2HexrdZQAZ3UwfU8eqFwx64XSgXurgcZ6xD+GUArGIt1aoF+RNAb6s6gyJ1/sBjtiqJn+SLQwiTsjhTrgphwxdVo8COBzmfIYSwhX5SrPhzZuc7z1S8CnWg= 
  app: lu-java-app